# Generated by Django 3.0 on 2021-08-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20210804_2100'),
        ('news', '0002_newspost_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='ad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='advertising.Advertisement'),
        ),
    ]
