# Generated by Django 3.0 on 2021-08-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_auto_20210804_2100'),
        ('news', '0004_auto_20210805_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='ad',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='advertising.Advertisement'),
        ),
    ]
