# Generated by Django 3.0 on 2021-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company_name',
            field=models.CharField(default='Industry Dive', max_length=150),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='copy',
            field=models.TextField(default='Want to read more great stories? Sign up for a newsletter!', max_length=1000),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='logo',
            field=models.CharField(default='industry-dive.png', max_length=150),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='url',
            field=models.CharField(default='https://industrydive.com', max_length=150),
        ),
    ]
